/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hallgato
 */
public class GrafikusFelulet extends javax.swing.JFrame {
    private final Color gombokszine;
    private static JLabel[] tomb;
    private int x;
    private int y;

    /**
     * Creates new form GrafikusFelulet
     */
    public GrafikusFelulet() {
        initComponents();
        setLocationRelativeTo(null);
        gombokszine = menu2.getBackground();
        gombok();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlebar = new javax.swing.JPanel();
        kilepes = new javax.swing.JLabel();
        cim = new javax.swing.JLabel();
        menubar = new javax.swing.JPanel();
        menu1 = new javax.swing.JLabel();
        menu2 = new javax.swing.JLabel();
        menu3 = new javax.swing.JLabel();
        menu4 = new javax.swing.JLabel();
        fotarolo = new javax.swing.JPanel();
        visszajelzes = new javax.swing.JPanel();
        ladatarolo = new javax.swing.JPanel();
        tarolo3 = new javax.swing.JPanel();
        tarolo2 = new javax.swing.JPanel();
        tarolo1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        titlebar.setBackground(new java.awt.Color(60, 60, 60));
        titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlebarMouseDragged(evt);
            }
        });
        titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlebarMousePressed(evt);
            }
        });

        kilepes.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        kilepes.setForeground(new java.awt.Color(228, 228, 228));
        kilepes.setText("X");
        kilepes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kilepesMouseClicked(evt);
            }
        });

        cim.setFont(new java.awt.Font("Lato Semibold", 1, 18)); // NOI18N
        cim.setForeground(new java.awt.Color(255, 255, 255));
        cim.setText("Kincskereső");

        javax.swing.GroupLayout titlebarLayout = new javax.swing.GroupLayout(titlebar);
        titlebar.setLayout(titlebarLayout);
        titlebarLayout.setHorizontalGroup(
            titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlebarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cim, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kilepes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        titlebarLayout.setVerticalGroup(
            titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cim, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(kilepes))
        );

        menubar.setBackground(new java.awt.Color(172, 172, 172));

        menu1.setBackground(new java.awt.Color(102, 102, 102));
        menu1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        menu1.setForeground(new java.awt.Color(204, 204, 204));
        menu1.setText("Új játék");
        menu1.setOpaque(true);

        menu2.setBackground(new java.awt.Color(102, 102, 102));
        menu2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        menu2.setForeground(new java.awt.Color(204, 204, 204));
        menu2.setText("Megoldás");
        menu2.setOpaque(true);

        menu3.setBackground(new java.awt.Color(102, 102, 102));
        menu3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        menu3.setForeground(new java.awt.Color(204, 204, 204));
        menu3.setText("Kérdés");
        menu3.setOpaque(true);

        menu4.setBackground(new java.awt.Color(102, 102, 102));
        menu4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        menu4.setForeground(new java.awt.Color(204, 0, 51));
        menu4.setText("Kilépés");
        menu4.setOpaque(true);

        javax.swing.GroupLayout menubarLayout = new javax.swing.GroupLayout(menubar);
        menubar.setLayout(menubarLayout);
        menubarLayout.setHorizontalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
            .addComponent(menu4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menubarLayout.setVerticalGroup(
            menubarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menubarLayout.createSequentialGroup()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fotarolo.setBackground(new java.awt.Color(200, 200, 200));

        visszajelzes.setBackground(new java.awt.Color(159, 162, 163));

        javax.swing.GroupLayout visszajelzesLayout = new javax.swing.GroupLayout(visszajelzes);
        visszajelzes.setLayout(visszajelzesLayout);
        visszajelzesLayout.setHorizontalGroup(
            visszajelzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        visszajelzesLayout.setVerticalGroup(
            visszajelzesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        ladatarolo.setBackground(new java.awt.Color(200, 200, 200));

        javax.swing.GroupLayout tarolo3Layout = new javax.swing.GroupLayout(tarolo3);
        tarolo3.setLayout(tarolo3Layout);
        tarolo3Layout.setHorizontalGroup(
            tarolo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        tarolo3Layout.setVerticalGroup(
            tarolo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tarolo2Layout = new javax.swing.GroupLayout(tarolo2);
        tarolo2.setLayout(tarolo2Layout);
        tarolo2Layout.setHorizontalGroup(
            tarolo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        tarolo2Layout.setVerticalGroup(
            tarolo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tarolo1Layout = new javax.swing.GroupLayout(tarolo1);
        tarolo1.setLayout(tarolo1Layout);
        tarolo1Layout.setHorizontalGroup(
            tarolo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        tarolo1Layout.setVerticalGroup(
            tarolo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ladataroloLayout = new javax.swing.GroupLayout(ladatarolo);
        ladatarolo.setLayout(ladataroloLayout);
        ladataroloLayout.setHorizontalGroup(
            ladataroloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladataroloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tarolo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tarolo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tarolo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ladataroloLayout.setVerticalGroup(
            ladataroloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladataroloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ladataroloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tarolo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarolo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tarolo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout fotaroloLayout = new javax.swing.GroupLayout(fotarolo);
        fotarolo.setLayout(fotaroloLayout);
        fotaroloLayout.setHorizontalGroup(
            fotaroloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fotaroloLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(fotaroloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ladatarolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visszajelzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        fotaroloLayout.setVerticalGroup(
            fotaroloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fotaroloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ladatarolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(visszajelzes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menubar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(fotarolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fotarolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menubar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void mauseHover(int funkcio, JLabel panel, Color szin1, Color szin2) { //1=Text szinezés 2=Háttér szinezés
        if (funkcio == 1) {
            panel.addMouseListener(new MouseAdapter() {
                public void mouseEntered(MouseEvent evt) {
                    panel.setForeground(szin1);
                }

                public void mouseExited(MouseEvent evt) {
                    panel.setForeground(szin2);
                }
            });
        } else if (funkcio == 2) {
            panel.addMouseListener(new MouseAdapter() {
                public void mouseEntered(MouseEvent evt) {
                    panel.setBackground(szin1);
                }

                public void mouseExited(MouseEvent evt) {
                    panel.setBackground(szin2);
                }
            });
        }
    }

    private void gombok() {
        tomb = new JLabel[menubar.getComponentCount()];
        for (int i = 0; i < tomb.length; i++) {
            Component component = menubar.getComponent(i);
            if (component instanceof JLabel) {
                JLabel gomb = (JLabel) component;
                tomb[i] = gomb;
            }
        }
        mauseHover(1, kilepes, Color.red, Color.white);
        for (JLabel menugomb : tomb) {
            mauseHover(2, menugomb, Color.GRAY, gombokszine);
        }
    }
    private void kilepesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kilepesMouseClicked

        kilep();
        // TODO add your handling code here:
    }//GEN-LAST:event_kilepesMouseClicked

    private void titlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_titlebarMouseDragged

    private void titlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlebarMousePressed
        x = evt.getX();
        y = evt.getY();  // TODO add your handling code here:
    }//GEN-LAST:event_titlebarMousePressed
    private void kilep() {
        String[] gombok = {"Igen", "Nem"};
        int valasz = JOptionPane.showOptionDialog(null, "Biztosan szeretnél kilépni?", "Kilépés", JOptionPane.YES_NO_OPTION, 3, null, gombok, gombok[1]);
        if (valasz == 0) {
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrafikusFelulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrafikusFelulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrafikusFelulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrafikusFelulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrafikusFelulet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cim;
    private javax.swing.JPanel fotarolo;
    private javax.swing.JLabel kilepes;
    private javax.swing.JPanel ladatarolo;
    private javax.swing.JLabel menu1;
    private javax.swing.JLabel menu2;
    private javax.swing.JLabel menu3;
    private javax.swing.JLabel menu4;
    private javax.swing.JPanel menubar;
    private javax.swing.JPanel tarolo1;
    private javax.swing.JPanel tarolo2;
    private javax.swing.JPanel tarolo3;
    private javax.swing.JPanel titlebar;
    private javax.swing.JPanel visszajelzes;
    // End of variables declaration//GEN-END:variables
}
